### ISSUE TITLE
Capture d'image à la détection de mouvement

### ISSUE THREAD

**Issue by Elrhino** [Elrhino/camera#12]
Enregistrer l'image à la détection de mouvement, soir sur l'appareil, l'application desktop ou le cloud.

**Comment by fredbegin11** [comment]
yolo

**Comment by fredbegin11** [comment]
Capture fait, reste au user de pouvoir modifier le path à sa guise et possiblement intégration Cloud

**Comment by fredbegin11** [comment]
done
